import { Navigation } from "@/common/Navigation/page";
import type { Metadata } from "next";
import Providers from "../../utils/provider";
import StyledComponentsRegistry from "./registry";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <StyledComponentsRegistry>
            <Navigation />
            {children}
          </StyledComponentsRegistry>
        </Providers>
      </body>
    </html >
  );
}
