import type { Metadata } from "next";
import Providers from "../../utils/provider";
import StyledComponentsRegistry from "./registry";
import { Header } from "@/common/Header/page";
import ThemeClient from "../../utils/ThemeProvider";
import "./global.css";
import { Poppins } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: ["300", "400", "500", "700"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={poppins.className}>
      <body>
        <Providers>
          <ThemeClient>
            <StyledComponentsRegistry>
              <Header />
              {children}
            </StyledComponentsRegistry>
          </ThemeClient>
        </Providers>
      </body>
    </html >
  );
}
